# Generated by Django 2.1.5 on 2019-03-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_on_behalf_of_others',
            field=models.BooleanField(default=False),
        ),
    ]
