# Generated by Django 2.1 on 2018-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_add_files_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
