# Generated by Django 2.2.4 on 2019-08-30 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notebook_revisions_most_recent_first'),
        ('files', '0001_add_file_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('update_interval', models.DurationField(choices=[(datetime.timedelta(days=1), 'daily'), (datetime.timedelta(days=7), 'weekly')], null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.Notebook')),
            ],
            options={
                'verbose_name': 'File Source',
                'verbose_name_plural': 'File Sources',
                'db_table': 'file_source',
                'ordering': ('id',),
                'unique_together': {('notebook', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='FileUpdateOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=32)),
                ('failure_reason', models.CharField(max_length=128, null=True)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.FileSource')),
            ],
            options={
                'verbose_name': 'File Update Operation',
                'verbose_name_plural': 'File Update Operations',
                'db_table': 'file_update_operation',
                'ordering': ('id',),
            },
        ),
    ]
