# Generated by Django 2.2.2 on 2019-07-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notebook_revisions_most_recent_first'),
        ('files', '0001_add_file_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120)),
                ('source', models.URLField()),
                ('update_interval', models.DurationField(null=True)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.File')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.Notebook')),
            ],
            options={
                'verbose_name': 'File Source',
                'verbose_name_plural': 'File Sources',
                'db_table': 'file_source',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FileUpdateOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'running'), (2, 'completed')], default=0)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.FileSource')),
            ],
            options={
                'db_table': 'file_operation',
            },
        ),
    ]
