# Generated by Django 2.1 on 2018-09-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
        ('files', '0002_use_datetime_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='filename',
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('notebook', 'filename')},
        ),
    ]
