# Generated by Django 2.2.3 on 2019-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notebook_revisions_most_recent_first'),
        ('files', '0002_add_file_sources_and_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupdateoperation',
            options={'ordering': ('id',), 'verbose_name': 'File Update Operation', 'verbose_name_plural': 'File Update Operations'},
        ),
        migrations.RenameField(
            model_name='filesource',
            old_name='source',
            new_name='url',
        ),
        migrations.AddField(
            model_name='fileupdateoperation',
            name='failure_reason',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fileupdateoperation',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'running'), (2, 'completed'), (3, 'failed')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='filesource',
            unique_together={('notebook', 'filename')},
        ),
        migrations.RemoveField(
            model_name='filesource',
            name='file',
        ),
    ]
