# Generated by Django 2.2.5 on 2019-09-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_file_sources_and_operations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
    ]
