# Generated by Django 2.2.5 on 2019-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_saner_table_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesource',
            name='url',
            field=models.URLField(max_length=8192),
        ),
    ]
