# Generated by Django 2.2.3 on 2019-07-10 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20190705_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesource',
            name='update_interval',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), 'daily'), (datetime.timedelta(days=7), 'weekly')], null=True),
        ),
    ]
