# Generated by Django 2.2.3 on 2019-08-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_add_scheduled_field_to_file_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupdateoperation',
            old_name='ended',
            new_name='ended_at',
        ),
        migrations.RenameField(
            model_name='fileupdateoperation',
            old_name='scheduled',
            new_name='scheduled_at',
        ),
        migrations.RenameField(
            model_name='fileupdateoperation',
            old_name='started',
            new_name='started_at',
        ),
        migrations.AlterField(
            model_name='fileupdateoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=32),
        ),
    ]
