# Generated by Django 2.2.5 on 2019-09-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_increase_max_size_of_file_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupdateoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
