# Generated by Django 2.2.4 on 2019-08-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_fixups1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileupdateoperation',
            table='file_update_operation',
        ),
    ]
