# Generated by Django 2.2.5 on 2019-10-01 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
        ('files', '0005_capitalized_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime when the file was first created'),
        ),
        migrations.AddField(
            model_name='file',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, help_text='The datetime when the file was last refreshed at', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='remote_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remote.RemoteOperation'),
        ),
    ]
