# Generated by Django 2.0.7 on 2018-07-27 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='NotebookRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='notebooks.Notebook')),
            ],
            options={
                'verbose_name': 'Notebook Revision',
                'verbose_name_plural': 'Notebook Revisions',
                'ordering': ('created',),
            },
        ),
    ]
