# Generated by Django 2.1.4 on 2019-02-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_notebook_forked_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebookrevision',
            options={'ordering': ('-created',), 'verbose_name': 'Notebook Revision', 'verbose_name_plural': 'Notebook Revisions'},
        ),
    ]
