# Generated by Django 2.2.7 on 2019-11-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_saner_table_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookrevision',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
