# Generated by Django 2.2.7 on 2019-12-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_enable_blank_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookrevision',
            name='is_draft',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
